extends Node

var LISA_FIRST_PHONE = load("res://data/game_stages/phone_message/lisa_first_phone/gs_lisa_first_phone.tres")
var POKER_GIRLS_FIRST_PHONE = load("res://data/game_stages/phone_message/poker_girls_first_phone/gs_poker_girls_first_phone.tres")
var ASHELY_INTRODUCE_AMY = load("res://data/game_stages/phone_message/ashely_introduce_amy/gs_ashely_introduce_amy.tres")
var CHAD_UNBLOCK_LISA = load("res://data/game_stages/phone_message/chad_unblock_lisa/gs_chad_unblock_lisa.tres")
var LISA_BLOCKED = load("res://data/game_stages/phone_message/lisa_blocked/gs_lisa_blocked.tres")
var LISA_AFTER_UNBLOCK = load("res://data/game_stages/phone_message/lisa_after_unblock/gs_lisa_after_unblock.tres")
var ASHELY_THEATER_PHONE = load("res://data/game_stages/phone_message/ashely_theater_phone/gs_ashely_theater_phone.tres")
var ANA_PHONE_INTRO = load("res://data/game_stages/phone_message/ana_phone_intro/gs_ana_phone_intro.tres")
var ASHELY_BAR_POKER_AFTER = load("res://data/game_stages/phone_message/ashely_bar_poker_message_after/gs_ashely_bar_poker_message_after.tres")
var ASHELY_BAR_POKER_BEFORE = load("res://data/game_stages/phone_message/ashely_bar_poker_message/gs_ashely_bar_poker_message.tres")
var ANNA_PHONE_MESSAGE_LYRIC = load("res://data/game_stages/phone_message/anna_phone_message_lyric/gs_anna_phone_message_lyric.tres")
var LISA_BEACH_BEFORE_MESSAGE = load("res://data/game_stages/phone_message/lisa_beach_message/gs_lisa_beach_message.tres")
var ANNA_CLASS_MESSAGE = load("res://data/game_stages/phone_message/anna_class_phone/gs_anna_class_phone.tres")
var LISA_SP_PHONE = load("res://data/game_stages/phone_message/lisa_sp_poker_phone/gs_lisa_sp_poker_phone.tres")
var AMY_PLUTO_PHONE = load("res://data/game_stages/phone_message/amy_phone_with_pluto_1/gs_amy_phone_with_pluto_1.tres")
var AMY_AFTER_PLUTO_PHONE = load("res://data/game_stages/phone_message/amy_phone_after_pluto_1/gs_amy_phone_after_pluto_1.tres")
var ASHELY_HOLIDAY_PHONE = load("res://data/game_stages/phone_message/ashely_kitchen_phone/gs_ashely_kitchen_phone.tres")
var LISA_WINTER = load("res://data/game_stages/phone_message/lisa_winter/gs_lisa_winter.tres")

#selectable events 
var LISA_FIRST_MARKET_DATE = load("res://data/game_stages/vn/lisa_first_market_date/gs_lisa_first_market_date.tres")
var ASHELY_FIRST_PARK_DATE = load("res://data/game_stages/vn/ashely_first_park_date/gs_ashely_first_park_date.tres")
var ANA_MARKET_INTRO = load("res://data/game_stages/vn/ana_shop_meeting/gs_ana_shop_meeting.tres")
var AMY_POKER_HALL_INTRO = load("res://data/game_stages/vn/amy_poker_hall_intro/gs_amy_poker_hall_intro.tres")
var LISA_PARK_TRAINING = load("res://data/game_stages/vn/lisa_park_training/gs_lisa_park_training.tres")
var ASHELY_THEATER = load("res://data/game_stages/vn/ashely_theater/gs_ashely_theater.tres")
var ANNA_BURGER = load("res://data/game_stages/vn/anna_burger_before_date/gs_anna_burger_before_date.tres")
var ASHELY_POKER = load("res://data/game_stages/vn/ashely_bar_before_poker/gs_ashely_bar_before_poker.tres")
var LISA_BEACH_BEFORE = load("res://data/game_stages/vn/lisa_beach_intro/gs_lisa_beach_intro.tres")
var ANNA_CLASS = load("res://data/game_stages/vn/anna_class/gs_anna_class.tres")
var LISA_SP_INTRO = load("res://data/game_stages/vn/lisa_sp_poker_intro/gs_lisa_sp_poker_intro.tres")
var AMY_LISA_DISCOVERY = load("res://data/game_stages/vn/amy_lisa_discovery/gs_amy_lisa_discovery.tres")
var UNLOCK_CHRISTMAS = load("res://data/game_stages/vn/activate_christmas_1/gs_activate_christmas_1.tres")
